### ISSUE TITLE
XRCE multithreading not supported for this platform - FreeRTOS - wrong flag

### ISSUE THREAD

**Issue by bjv-capra** [eProsima/Micro-XRCE-DDS-Client#233]
From https://github.com/micro-ROS/micro_ros_setup/issues/312
I was trying to enable multithread support, however, I got 
```
eProsima/Micro-XRCE-DDS-Client/src/c/profile/multithread/multithread.c:23:2: error: #error XRCE multithreading not supported for this platform.
```
By quickly skimming the code, it seems the wrong flag is used for FreeRTOS. I'm using FreeRTOS+TCP, on the base [CMakeLists.txt](https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/foxy/CMakeLists.txt), this sets `UCLIENT_PLATFORM_FREERTOS_PLUS_TCP`, on the other hand, https://github.com/eProsima/Micro-XRCE-DDS-Client/blob/foxy/src/c/profile/multithread/multithread.c#L13 expects to be `PLATFORM_NAME_FREERTOS`. As a workaround, I can set the flag on my colcon meta, but I think it's not the intended behavior.

**Comment by pablogs9** [comment]
Yes, this was the intended behavior because FreeRTOS does not have a common set of flags for checking when it is being used, so the user is in charge of defining `PLATFORM_NAME_FREERTOS`. The point is that `UCLIENT_PLATFORM_FREERTOS_PLUS_TCP` only refers to a TCP/UDP transport layer and FreeRTOS can be used with other transports.
